const leadsMockData = [
  {
    id: 1,
    mobile: '1234567890',
    customerName: 'John Doe',
    email: 'johndoe@example.com',
    contactPersonNumber: '1122334455',
    district: 'AnyDistrict',
    lastFollowUpDate: '2024-06-01',
    sourceOfLead: 'Website',
    leadStatus: 'New',
    assignProduct: 'Laptop',
    priority: 'High'
  },
  {
    id: 2,
    mobile: '2345678901',
    customerName: 'Alice Smith',
    email: 'alicesmith@example.com',
    contactPersonNumber: '2233445566',
    district: 'OtherDistrict',
    lastFollowUpDate: '2024-06-02',
    sourceOfLead: 'Referral',
    leadStatus: 'Contacted',
    assignProduct: 'Chair',
    priority: 'Medium'
  },
  {
    id: 3,
    mobile: '3456789012',
    customerName: 'Bob Johnson',
    email: 'bobjohnson@example.com',
    contactPersonNumber: '3344556677',
    district: 'District 3',
    lastFollowUpDate: '2024-06-03',
    sourceOfLead: 'Email Campaign',
    leadStatus: 'Qualified',
    assignProduct: 'Table',
    priority: 'Low'
  },
  {
    id: 4,
    mobile: '4567890123',
    customerName: 'Charlie Brown',
    email: 'charliebrown@example.com',
    contactPersonNumber: '4455667788',
    district: 'District 4',
    lastFollowUpDate: '2024-06-04',
    sourceOfLead: 'Social Media',
    leadStatus: 'Lost',
    assignProduct: 'Phone',
    priority: 'Medium'
  },
  {
    id: 5,
    mobile: '5678901234',
    customerName: 'David Wilson',
    email: 'davidwilson@example.com',
    contactPersonNumber: '5566778899',
    district: 'District 5',
    lastFollowUpDate: '2024-06-05',
    sourceOfLead: 'Direct Mail',
    leadStatus: 'New',
    assignProduct: 'Monitor',
    priority: 'High'
  },
  {
    id: 6,
    mobile: '6789012345',
    customerName: 'Eve Adams',
    email: 'eveadams@example.com',
    contactPersonNumber: '6677889900',
    district: 'District 6',
    lastFollowUpDate: '2024-06-06',
    sourceOfLead: 'Trade Show',
    leadStatus: 'Contacted',
    assignProduct: 'Printer',
    priority: 'Low'
  },
  {
    id: 7,
    mobile: '7890123456',
    customerName: 'Frank Clark',
    email: 'frankclark@example.com',
    contactPersonNumber: '7788990011',
    district: 'District 7',
    lastFollowUpDate: '2024-06-07',
    sourceOfLead: 'Website',
    leadStatus: 'Qualified',
    assignProduct: 'Scanner',
    priority: 'Medium'
  },
  {
    id: 8,
    mobile: '8901234567',
    customerName: 'Grace Lee',
    email: 'gracelee@example.com',
    contactPersonNumber: '8899001122',
    district: 'District 8',
    lastFollowUpDate: '2024-06-08',
    sourceOfLead: 'Referral',
    leadStatus: 'Lost',
    assignProduct: 'Keyboard',
    priority: 'High'
  },
  {
    id: 9,
    mobile: '9012345678',
    customerName: 'Henry Green',
    email: 'henrygreen@example.com',
    contactPersonNumber: '9900112233',
    district: 'District 9',
    lastFollowUpDate: '2024-06-09',
    sourceOfLead: 'Email Campaign',
    leadStatus: 'New',
    assignProduct: 'Mouse',
    priority: 'Low'
  },
  {
    id: 10,
    mobile: '0123456789',
    customerName: 'Ivy Scott',
    email: 'ivyscott@example.com',
    contactPersonNumber: '1011122334',
    district: 'District 10',
    lastFollowUpDate: '2024-06-10',
    sourceOfLead: 'Social Media',
    leadStatus: 'Contacted',
    assignProduct: 'Headset',
    priority: 'Medium'
  },
  {
    id: 11,
    mobile: '1111111111',
    customerName: 'Jake White',
    email: 'jakewhite@example.com',
    contactPersonNumber: '1213141516',
    district: 'District 11',
    lastFollowUpDate: '2024-06-11',
    sourceOfLead: 'Direct Mail',
    leadStatus: 'Qualified',
    assignProduct: 'Speaker',
    priority: 'High'
  },
  {
    id: 12,
    mobile: '2222222222',
    customerName: 'Karen Black',
    email: 'karenblack@example.com',
    contactPersonNumber: '1718192021',
    district: 'District 12',
    lastFollowUpDate: '2024-06-12',
    sourceOfLead: 'Trade Show',
    leadStatus: 'Lost',
    assignProduct: 'Webcam',
    priority: 'Low'
  },
  {
    id: 13,
    mobile: '3333333333',
    customerName: 'Leo Harris',
    email: 'leoharris@example.com',
    contactPersonNumber: '2223242526',
    district: 'District 13',
    lastFollowUpDate: '2024-06-13',
    sourceOfLead: 'Website',
    leadStatus: 'New',
    assignProduct: 'Router',
    priority: 'Medium'
  },
  {
    id: 14,
    mobile: '4444444444',
    customerName: 'Mia Martin',
    email: 'miamartin@example.com',
    contactPersonNumber: '2728293031',
    district: 'District 14',
    lastFollowUpDate: '2024-06-14',
    sourceOfLead: 'Referral',
    leadStatus: 'Contacted',
    assignProduct: 'Switch',
    priority: 'High'
  },
  {
    id: 15,
    mobile: '5555555555',
    customerName: 'Nathan Carter',
    email: 'nathancarter@example.com',
    contactPersonNumber: '3233343536',
    district: 'District 15',
    lastFollowUpDate: '2024-06-15',
    sourceOfLead: 'Email Campaign',
    leadStatus: 'Qualified',
    assignProduct: 'Modem',
    priority: 'Low'
  },
  {
    id: 16,
    mobile: '6666666666',
    customerName: 'Olivia Roberts',
    email: 'oliviaroberts@example.com',
    contactPersonNumber: '3738394041',
    district: 'District 16',
    lastFollowUpDate: '2024-06-16',
    sourceOfLead: 'Social Media',
    leadStatus: 'Lost',
    assignProduct: 'Cable',
    priority: 'Medium'
  },
  {
    id: 17,
    mobile: '7777777777',
    customerName: 'Paul Mitchell',
    email: 'paulmitchell@example.com',
    contactPersonNumber: '4243444546',
    district: 'District 17',
    lastFollowUpDate: '2024-06-17',
    sourceOfLead: 'Direct Mail',
    leadStatus: 'New',
    assignProduct: 'Adapter',
    priority: 'High'
  },
  {
    id: 18,
    mobile: '8888888888',
    customerName: 'Quinn Turner',
    email: 'quinnturner@example.com',
    contactPersonNumber: '4748495051',
    district: 'District 18',
    lastFollowUpDate: '2024-06-18',
    sourceOfLead: 'Trade Show',
    leadStatus: 'Contacted',
    assignProduct: 'Dock',
    priority: 'Low'
  },
  {
    id: 19,
    mobile: '9999999999',
    customerName: 'Ruby Baker',
    email: 'rubybaker@example.com',
    contactPersonNumber: '5253545556',
    district: 'District 19',
    lastFollowUpDate: '2024-06-19',
    sourceOfLead: 'Website',
    leadStatus: 'Qualified',
    assignProduct: 'Charger',
    priority: 'Medium'
  },
  {
    id: 20,
    mobile: '0000000000',
    customerName: 'Sam Parker',
    email: 'samparker@example.com',
    contactPersonNumber: '5758596061',
    district: 'District 20',
    lastFollowUpDate: '2024-06-20',
    sourceOfLead: 'Referral',
    leadStatus: 'Lost',
    assignProduct: 'Battery',
    priority: 'High'
  },
  {
    id: 21,
    mobile: '1010101010',
    customerName: 'Tom Collins',
    email: 'tomcollins@example.com',
    contactPersonNumber: '6263646566',
    district: 'District 21',
    lastFollowUpDate: '2024-06-21',
    sourceOfLead: 'Email Campaign',
    leadStatus: 'New',
    assignProduct: 'SSD',
    priority: 'Low'
  },
  {
    id: 22,
    mobile: '1111111112',
    customerName: 'Uma Bell',
    email: 'umabell@example.com',
    contactPersonNumber: '6768697071',
    district: 'District 22',
    lastFollowUpDate: '2024-06-22',
    sourceOfLead: 'Social Media',
    leadStatus: 'Contacted',
    assignProduct: 'RAM',
    priority: 'Medium'
  },
  {
    id: 23,
    mobile: '1212121212',
    customerName: 'Vera Morris',
    email: 'veramorris@example.com',
    contactPersonNumber: '7273747576',
    district: 'District 23',
    lastFollowUpDate: '2024-06-23',
    sourceOfLead: 'Direct Mail',
    leadStatus: 'Qualified',
    assignProduct: 'CPU',
    priority: 'High'
  },
  {
    id: 24,
    mobile: '1313131313',
    customerName: 'Will Edwards',
    email: 'willedwards@example.com',
    contactPersonNumber: '7778798081',
    district: 'District 24',
    lastFollowUpDate: '2024-06-24',
    sourceOfLead: 'Trade Show',
    leadStatus: 'Lost',
    assignProduct: 'GPU',
    priority: 'Low'
  },
  {
    id: 25,
    mobile: '1414141414',
    customerName: 'Xena Wright',
    email: 'xenawright@example.com',
    contactPersonNumber: '8283848586',
    district: 'District 25',
    lastFollowUpDate: '2024-06-25',
    sourceOfLead: 'Website',
    leadStatus: 'New',
    assignProduct: 'Motherboard',
    priority: 'Medium'
  },
  {
    id: 26,
    mobile: '1515151515',
    customerName: 'Yara King',
    email: 'yaraking@example.com',
    contactPersonNumber: '8788899091',
    district: 'District 26',
    lastFollowUpDate: '2024-06-26',
    sourceOfLead: 'Referral',
    leadStatus: 'Contacted',
    assignProduct: 'Power Supply',
    priority: 'High'
  },
  {
    id: 27,
    mobile: '1616161616',
    customerName: 'Zane Hill',
    email: 'zanehill@example.com',
    contactPersonNumber: '9293949596',
    district: 'District 27',
    lastFollowUpDate: '2024-06-27',
    sourceOfLead: 'Email Campaign',
    leadStatus: 'Qualified',
    assignProduct: 'Case',
    priority: 'Low'
  },
  {
    id: 28,
    mobile: '1717171717',
    customerName: 'Abby Foster',
    email: 'abbyfoster@example.com',
    contactPersonNumber: '9798991001',
    district: 'District 28',
    lastFollowUpDate: '2024-06-28',
    sourceOfLead: 'Social Media',
    leadStatus: 'Lost',
    assignProduct: 'Fan',
    priority: 'Medium'
  },
  {
    id: 29,
    mobile: '1818181818',
    customerName: 'Brian Allen',
    email: 'brianallen@example.com',
    contactPersonNumber: '1011021034',
    district: 'District 29',
    lastFollowUpDate: '2024-06-29',
    sourceOfLead: 'Direct Mail',
    leadStatus: 'New',
    assignProduct: 'Cooler',
    priority: 'High'
  },
  {
    id: 30,
    mobile: '1919191919',
    customerName: 'Cathy Brooks',
    email: 'cathybrooks@example.com',
    contactPersonNumber: '1041051067',
    district: 'District 30',
    lastFollowUpDate: '2024-06-30',
    sourceOfLead: 'Trade Show',
    leadStatus: 'Contacted',
    assignProduct: 'Thermal Paste',
    priority: 'Low'
  },
  {
    id: 31,
    mobile: '2020202020',
    customerName: 'Danielle Cook',
    email: 'daniellecook@example.com',
    contactPersonNumber: '1071081098',
    district: 'District 31',
    lastFollowUpDate: '2024-07-01',
    sourceOfLead: 'Website',
    leadStatus: 'Qualified',
    assignProduct: 'Cable Management',
    priority: 'Medium'
  },
  {
    id: 32,
    mobile: '2121212121',
    customerName: 'Eli Phillips',
    email: 'eliphillips@example.com',
    contactPersonNumber: '1101111129',
    district: 'District 32',
    lastFollowUpDate: '2024-07-02',
    sourceOfLead: 'Referral',
    leadStatus: 'Lost',
    assignProduct: 'Dust Filter',
    priority: 'High'
  },
  {
    id: 33,
    mobile: '2222222222',
    customerName: 'Faith Reed',
    email: 'faithreed@example.com',
    contactPersonNumber: '1131141150',
    district: 'District 33',
    lastFollowUpDate: '2024-07-03',
    sourceOfLead: 'Email Campaign',
    leadStatus: 'New',
    assignProduct: 'RGB Lighting',
    priority: 'Low'
  },
  {
    id: 34,
    mobile: '2323232323',
    customerName: 'George Barnes',
    email: 'georgebarnes@example.com',
    contactPersonNumber: '1161171181',
    district: 'District 34',
    lastFollowUpDate: '2024-07-04',
    sourceOfLead: 'Social Media',
    leadStatus: 'Contacted',
    assignProduct: 'Cable Sleeving',
    priority: 'Medium'
  },
  {
    id: 35,
    mobile: '2424242424',
    customerName: 'Hannah Perry',
    email: 'hannahperry@example.com',
    contactPersonNumber: '1191201212',
    district: 'District 35',
    lastFollowUpDate: '2024-07-05',
    sourceOfLead: 'Direct Mail',
    leadStatus: 'Qualified',
    assignProduct: 'UPS',
    priority: 'High'
  },
  {
    id: 36,
    mobile: '2525252525',
    customerName: 'Ian Rivera',
    email: 'ianrivera@example.com',
    contactPersonNumber: '1221231243',
    district: 'District 36',
    lastFollowUpDate: '2024-07-06',
    sourceOfLead: 'Trade Show',
    leadStatus: 'Lost',
    assignProduct: 'Power Strip',
    priority: 'Low'
  }
];

export default leadsMockData;
